version: "3.9"

services:
  # CONTAINER DATABASE POSTGRES
  db:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=duan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  # CONTAINER WEB DJANGO
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./duan:/duan_be
    environment:
      - POSTGRES_NAME=duan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    command:
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
